spring.application.name=API-Marketplace
server.port=5443

# Activem la consola de la base de dades H2
spring.h2.console.enabled=true

# Configuració de la base de dades
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace_1
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=Pau_admin
spring.datasource.password=1234



# Indicacions per a Hibernate sobre la gestió dels canvis a la base de dades
spring.jpa.hibernate.ddl-auto=update